repository:
  name: aries-framework-go-ext
  description: null
  homepage: https://wiki.hyperledger.org/display/aries
  default_branch: main
  has_downloads: false
  has_issues: true
  has_projects: false
  has_wiki: false
  archived: true
  private: false
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
