# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

coverage:
  status:
    project:
      default: false
      component:
        target: 85%
        informational: true
        paths:
          - component
    patch:
      default:
        target: 85%
        only_pulls: true
