#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
name: repolint
on:
  push:
  pull_request:
jobs:
  license:
    name: Apache license
    timeout-minutes: 10
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Checks Apache license
        timeout-minutes: 10
        run: make license

  repoLint:
    name: repolint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1.0.0
      - name: repolinter
        uses: philips-labs/github-action-repolinter@v1.0.0
        env:
          CUSTOM_REPOLINT_FILE: .repolint.json