#
# Copyright Gen Digital Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
name: vc-status
on:
  push:
    paths:
      - 'component/vc/status/**'
  pull_request:
    paths:
      - 'component/vc/status/**'
jobs:
  linter:
    name: Go linter
    timeout-minutes: 10
    env:
      LINT_PATH: component/vc/status
      GOLANGCI_LINT_IMAGE: "golangci/golangci-lint:v1.54.2"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Checks linter
        timeout-minutes: 10
        run: make lint
  unitTest:
    name: Unit test
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    env:
      UNIT_TESTS_PATH: component/vc/status
    steps:
      - name: Setup Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
        id: go

      - uses: actions/checkout@v2

      - name: Run unit test
        timeout-minutes: 15
        run: make unit-test

      - name: Upload coverage to Codecov
        timeout-minutes: 10
        if: github.repository == 'hyperledger/aries-framework-go-ext'
        uses: codecov/codecov-action@v1.0.14
        with:
          file: ./coverage.out

