#
# Copyright Scoir, Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
name: vdr-indy
on:
  push:
    paths:
      - 'component/vdr/indy/**'
  pull_request:
    paths:
      - 'component/vdr/indy/**'
jobs:
  linter:
    name: Go linter
    timeout-minutes: 10
    env:
      LINT_PATH: component/vdr/indy
      GOLANGCI_LINT_IMAGE: "canislabs/golangci-lint:latest"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Checks linter
        timeout-minutes: 10
        run: make lint
  unitTest:
    name: Unit test
    runs-on: ubuntu-18.04
    container: canislabs/canisbuild:golang-1.15
    timeout-minutes: 15
    env:
      UNIT_TESTS_PATH: component/vdr/indy
    steps:
      - name: Setup Go 1.15
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
        id: go

      - uses: actions/checkout@v2

      - name: Run unit test
        timeout-minutes: 15
        run: make unit-test

      - name: Upload coverage to Codecov
        timeout-minutes: 10
        if: github.repository == 'hyperledger/aries-framework-go-ext'
        uses: codecov/codecov-action@v1.0.13
        with:
          file: ./coverage.txt
