#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
name: vdr-sidetree
on:
  push:
    paths:
      - 'component/vdr/sidetree/**'
  pull_request:
    paths:
      - 'component/vdr/sidetree/**'
jobs:
  linter:
    name: Go linter
    timeout-minutes: 10
    env:
      LINT_PATH: component/vdr/sidetree
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Checks linter
        timeout-minutes: 10
        run: make lint
  unitTest:
    name: Unit test
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    env:
      UNIT_TESTS_PATH: component/vdr/sidetree
    steps:
      - name: Setup Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go

      - uses: actions/checkout@v2

      - name: Run unit test
        timeout-minutes: 15
        run: make unit-test

      - name: Upload coverage to Codecov
        timeout-minutes: 10
        if: github.repository == 'hyperledger/aries-framework-go-ext'
        uses: codecov/codecov-action@v1.0.14
        with:
          file: ./coverage.out
