#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
name: vdr-orb
on:
  push:
    paths:
      - 'component/vdr/orb/**'
      - 'test/bdd/vdr/orb/**'
  pull_request:
    paths:
      - 'component/vdr/orb/**'
      - 'test/bdd/vdr/orb/**'
jobs:
  linter:
    name: Go linter
    timeout-minutes: 10
    env:
      LINT_PATH: component/vdr/orb
      GOLANGCI_LINT_IMAGE: "golangci/golangci-lint:v1.50.0"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Checks linter
        timeout-minutes: 10
        run: make lint
  unitTest:
    name: Unit test
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    env:
      UNIT_TESTS_PATH: component/vdr/orb
    steps:
      - name: Setup Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go

      - uses: actions/checkout@v2

      - name: Run unit test
        timeout-minutes: 15
        run: make unit-test

      - name: Upload coverage to Codecov
        timeout-minutes: 10
        if: github.repository == 'hyperledger/aries-framework-go-ext'
        uses: codecov/codecov-action@v1.0.14
        with:
          file: ./coverage.out
  bddtest:
    name: BDD test
    timeout-minutes: 30
    runs-on: ubuntu-18.04
    steps:
      - name: Setup Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
        id: go

      - uses: actions/checkout@v2

      - name: BDD test
        timeout-minutes: 20
        run: |
          echo '127.0.0.1 testnet.orb.local' | sudo tee -a /etc/hosts
          make vdr-orb-bdd-test
